FROM nginx:latest
RUN echo $(ls /etc/nginx/)

RUN rm -r /etc/nginx/conf.d/*
ADD ./_docker/nginx/conf.d /etc/nginx/conf.d

COPY --from=opbeans/opbeans-frontend:latest /app/build  /var/www/public
### To get the client name/version from package.json
COPY --from=opbeans/opbeans-frontend:latest /app/package.json /var/www/public/package.json

