version: '2.1'

services:
  opbeans-python:
    image: opbeans/opbeans-python:latest
    container_name: opbeans-python
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    environment:
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-opbeans-python}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-http://apm-server:8200}
      - ELASTIC_APM_JS_SERVER_URL=${ELASTIC_APM_JS_SERVER_URL:-http://localhost:8200}
      - ELASTIC_APM_JS_SERVICE_NAME=${ELASTIC_APM_JS_SERVICE_NAME:-opbeans-react}
      - ELASTIC_APM_FLUSH_INTERVAL=5
      - ELASTIC_APM_TRANSACTION_MAX_SPANS=50
      - ELASTIC_APM_TRANSACTION_SAMPLE_RATE=0.5
      - ELASTIC_APM_SOURCE_LINES_ERROR_APP_FRAMES
      - ELASTIC_APM_SOURCE_LINES_SPAN_APP_FRAMES=5
      - ELASTIC_APM_SOURCE_LINES_ERROR_LIBRARY_FRAMES
      - ELASTIC_APM_SOURCE_LINES_SPAN_LIBRARY_FRAMES
      - ELASTIC_APM_ENVIRONMENT=production
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - DATABASE_URL=sqlite:////app/demo/db.sql
    depends_on:
      redis:
        condition: service_healthy
      apm-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://opbeans-python:3000/"]
      interval: 10s
      retries: 10

  opbeans-java:
    image: opbeans/opbeans-java:latest
    container_name: opbeans-java
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    environment:
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-opbeans-java}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-http://apm-server:8200}
      - ELASTIC_APM_APPLICATION_PACKAGES=co.elastic.apm.opbeans
      - ELASTIC_APM_JS_SERVER_URL=${ELASTIC_APM_JS_SERVER_URL:-http://localhost:8200}
      - OPBEANS_SERVER_PORT=${OPBEANS_SERVER_PORT:-3000}
      - ELASTIC_APM_ENABLE_LOG_CORRELATION=true
      - ELASTIC_APM_ENVIRONMENT=production
      - OTEL_RESOURCE_ATTRIBUTES=service.name=${ELASTIC_APM_SERVICE_NAME:-opbeans-java},deployment.environment=production
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://apm-server:8200}
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - APM_AGENT_TYPE=${APM_AGENT_TYPE:-elasticapm}
    depends_on:
      apm-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://opbeans-java:3000/"]
      interval: 10s
      retries: 10

  redis:
    image: redis:4
    ports:
      - 6379:6379
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s

  wait:
    image: busybox
    depends_on:
      opbeans-python:
        condition: service_healthy
      opbeans-java:
        condition: service_healthy
